services:
  navidrome:
    build: 
      context: ./navidrome
      dockerfile: Dockerfile
    container_name: navidrome
    volumes:
      - /home/${USER:-}/def-not-spotify/navidrome-data:/data
      - /home/${USER:-}/def-not-spotify/music:/music
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_PORT: 4533
      ND_YTDLPCOOKIESFILE: ${ND_YTDLPCOOKIESFILE:-}
      ND_YTDLPUSERNAME: ${ND_YTDLPUSERNAME:-}
      ND_YTDLPPASSWORD: ${ND_YTDLPPASSWORD:-}
    restart: unless-stopped
    networks:
      - navidrome-network

  navidrome-song-downloader:
    build:
      context: ./navidrome-song-downloader
      dockerfile: Dockerfile
    container_name: navidrome-song-downloader
    volumes:
      - /home/${USER:-}/def-not-spotify/music:/music
      - /home/${USER:-}/def-not-spotify/navidrome-data:/data
    restart: unless-stopped
    networks:
      - navidrome-network

  # navidrome-tunnel:
  #   container_name: navidrome-tunnel
  #   image: cloudflare/cloudflared:latest
  #   restart: always
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  #   depends_on:
  #     - navidrome
  #   networks:
  #     - navidrome-network

networks:
  navidrome-network:
    driver: bridge